flags: {}
resolver: lts-12.12
extra-deps:
- fltkhs-0.7.0.3
- fltkhs-themes-0.1.0.5
- load-font-0.1.0.2
- asset-bundle-0.1.0.1

nix:
  packages:
    - autoconf
    - pkgconfig
    - xorg.libX11
    - xorg.libXft
